spring:
  application:
    name: petfit
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/petfit
    username: postgres
    password: 95206326

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kakao:
    auth:
      admin: 74f521389d656a1e56c68d4223ccf874
      client: 84d27ea7be4ba339a95254c674c3c972
      redirect: http://localhost:8080/auth/kakao/login
      logout:
        redirect: http://localhost:8080/auth/kakao/logout

  jwt:
    issuer: cms3604@naver.com
    secret: ject-3rd-petfit
    access-token-time: 3600000  # 1 hour
    refresh-token-validity-seconds: 604800000  # 7 days

